### PR TITLE
feat: Add shortLabel prop to ShareButton

### PR DESCRIPTION
**Pull request by JF-Cozy**
To show short label when "shared with me" or "shared by me". It shows only "shared" in those cases.

### CODE REVIEW

**Review by Crash-- — CHANGES_REQUESTED** [review]
I don't think we should add this kind of props. 

WDYT about : 
```
<ShareButton 
labels={{
'sharedByMe': ...,
'shareWithMe': ...,
'shareCTA':
}} /> 
```
Or we could also export ShareButton without the withLocales. Like that you can pass the t you want without adding any props

**Comment by ptbrowne** [comment]
I wonder if `shared={true|false}` prop wouldn't be better, and then the label could be conditioned on this prop ? I think it would be a bit closer to the business rule ? I do not know so well the usecase so I may be mistaken.

**Comment by Crash--** [comment]
I don't think it's a good idea to add something like `shared={true|false}` . Does that mean that the document is shared? Or does that mean we want to display "shared" everywhere? 

I've an other option : dealing with the isMobile case directly in the ShareButton. I don't think we will one day display "Partagé avec moi" on a mobile screen. It really takes a lot a space. And since this component can be added everywhere, I'm wondering if the component should not deal itself with that case

After reviewing the first proposal, I think we can enhance it and makes it better by using "useShortLabel" true / false instead of shortLabel. At first, I though we're passing the "short label string" to that props

**Comment by JF-Cozy** [comment]
> After reviewing the first proposal, I think we can enhance it and makes it better by using "useShortLabel" true / false instead of shortLabel. At first, I though we're passing the "short label string" to that props

Oui très bien, c'est effectivement plus clair

**Review by Crash-- — APPROVED** [review]

**Pull request merged**
