### PR TITLE
(wip) feat(renovate-config-cozy): Automerge patch /minor versions of cozy libs

### PR DESCRIPTION
**Pull request by Crash--**
Just a try to have feedbacks.

What do you think of automerging all our new patch / minor versions of our cozy-* packages when their status check are green?

### CODE REVIEW

**Comment by edas** [comment]
Peut-être pas quand il y a un pin explicite, mais pour patch et minor, 👍

**Comment by ptbrowne** [comment]
:shipit:

**Comment by ptbrowne** [comment]
What is left to do ?

**Comment by Crash--** [comment]
Again: I need to find the time to run it on a repo to see the result

**Comment by Crash--** [comment]
I think I need a little help to test this configuration. 

I tried to run `renovate` in my machine for this repo, but I don't know how to tell to `renovate` to use my local configuration instead of the remote one. 

Someone has an idea?

**Comment by nono** [comment]
Ping @Crash--

**Comment by ptbrowne** [comment]
> I tried to run renovate in my machine for this repo, but I don't know how to tell to renovate to use my local configuration instead of the remote one.

Last time, I used a `renovate.json` file.

**Pull request closed without merging**
