### PR TITLE
Exit on failing git pull

### PR DESCRIPTION
**Pull request by gregorylegarec**
This PR avoid to continue release process when first git pull is failing.

### CODE REVIEW

**Comment by nono** [comment]
Ping @CPatchane 

By the way, can I suggest to use `set -e`? (see https://www.davidpashley.com/articles/writing-robust-shell-scripts/ for an explanation)

**Comment by ptbrowne** [comment]
I like to add to also `set -u` to fail on undefined variables. And `set -o pipefail` so that an exit code of 1 make the whole pipeline fail.

`set -euo pipefail`

**Comment by gregorylegarec** [comment]
Thanks, I will add this line and test again all the `cozy-release` commands, as soon as I got 30 minutes.

**Comment by CPatchane** [comment]
ping @gregorylegarec to add the `set -euo pipefail`

**Comment by nono** [comment]
Friendly reminder for @gregorylegarec :alarm_clock:

**Comment by CPatchane** [comment]
Is this PR still relevant @gregorylegarec?

**Comment by nono** [comment]
Ping @gregorylegarec

**Comment by gregorylegarec** [comment]
Still needing 30 minutes 😭

**Comment by nono** [comment]
Ping @gregorylegarec

**Comment by gregorylegarec** [comment]
I will not have time to finish this, moreover no one is using cozy-release except myself now.

**Pull request closed without merging**
