### PR TITLE
fix: Use data in vaultCipher relationship

### PR DESCRIPTION
**Pull request by Gara64**
See https://github.com/cozy/cozy-doctypes/blob/master/docs/README.md#external-relationships

### CODE REVIEW

**Comment by Gara64** [comment]
@y-lohse I'm already working on a migration job on the stack side, which will create a cipher for each account and add the relationship in the account

**Comment by y-lohse** [comment]
> @y-lohse I'm already working on a migration job on the stack side, which will create a cipher for each account and add the relationship in the account

I meant a migration for instances that have the relationship without `data`, for which things will break after this change. AFAIK it's only test instances though.

**Comment by Gara64** [comment]
> > @y-lohse I'm already working on a migration job on the stack side, which will create a cipher for each account and add the relationship in the account
> 
> I meant a migration for instances that have the relationship without `data`, for which things will break after this change. AFAIK it's only test instances though.

Yes, it's only testing instances for now, so I think it's safe :)

**Comment by ptbrowne** [comment]
> @y-lohse I'm already working on a migration job on the stack side, 

Is this a migration that will run on each Cozy ? Wouldn't it be simpler at least for deployment to do it with `ach batch` ?

**Comment by Gara64** [comment]
> > @y-lohse I'm already working on a migration job on the stack side,
> 
> Is this a migration that will run on each Cozy ? Wouldn't it be simpler at least for deployment to do it with `ach batch` ?

In this case we need the private key to decrypt credentials accounts, which should remain on the worker side, so it makes more sense to use a [migration job](https://docs.cozy.io/en/cozy-stack/workers/#migrations)

**Comment by ptbrowne** [comment]
TIL migration jobs, thanks 🎉

**Comment by Gara64** [comment]
ping @drazik is it ok for you?

**Comment by drazik** [comment]
Yes. Sorry I missed the first ping :(

**Pull request merged**
