### PR TITLE
chore: Mui/lab has to be in peerDep

### PR DESCRIPTION
**Pull request by Crash--**
We rely on /lab for some Harvest components. So let's add it to the peerDep section.

### CODE REVIEW

**Review by JF-Cozy — APPROVED** [review]
la dernière est `4.0.0-alpha.61`. Il faut spécifiquement la 60 ici ?

**Comment by Crash--** [comment]
I don't know this is what I have here https://github.com/cozy/cozy-home/blob/master/package.json#L38 

I don't want to broke something 🤸‍♂️

**Comment by trollepierre** [comment]
> la dernière est `4.0.0-alpha.61`. Il faut spécifiquement la 60 ici ?

I agree with @JF-Cozy , we should have used:
"@material-ui/lab": ">4.0.0-alpha.60",

**Comment by Crash--** [comment]
I'm not sure. This is an "alpha" version. There is nothing telling us that in alpha 61, 62 or else this component will be still there.

**Pull request merged**
