### PR TITLE
Interapp: Export correctly as default module

### PR DESCRIPTION
**Pull request by CPatchane**
As said in the readme, we should be able to do `import Intents from 'cozy-interapp'`

### CODE REVIEW

**Comment by ptbrowne** [comment]
Is it a breaking change ?

**Comment by CPatchane** [comment]
It's used by banks and sandbox so it is a breaking change. I change my commit to notice it 👍

**Comment by CPatchane** [comment]
@ptbrowne I added both to avoid a breaking change just for this

**Comment by ptbrowne** [comment]
:shipit: :)

**Pull request merged**
