### PR TITLE
fix(cozy-doctypes): Avoid es2015 export syntax

### PR DESCRIPTION
**Pull request by doubleface**
This allows nodejs to use not built version of cozy-doctypes

### CODE REVIEW

**Comment by Crash--** [comment]
I think I already asked this question, but what is the interest of not using the built version?

**Comment by ptbrowne** [comment]
I think adding https://www.npmjs.com/package/eslint-plugin-node and `"node/exports-style": ["error", "module.exports"],` would be beneficial here as we will forget that we cannot use export const here.

I also wonder why we cannot put the built version as the preferred `main` in package.json.

**Comment by doubleface** [comment]
@Crash-- @ptbrowne I did not do this choice of putting the source version for node, but the only advantage I see is that the async/await stack trace is easier to read.

**Comment by ptbrowne** [comment]
> but the only advantage I see is that the async/await stack trace is easier to read.

It seems a good reason to me, and also we know that we are on nodejs runtime with `main` so there is no need to use transpilation here (apart from es6 modules not being supported). What do you think of th eslint rule ?

**Comment by ptbrowne** [comment]
I've added a bit of doc on environments: https://github.com/cozy/cozy-libs/pull/714

**Comment by Crash--** [comment]
> but the only advantage I see is that the async/await stack trace is easier to read

Good reason to me also! 

> I've added a bit of doc on environments: #714
Thanks! 

> What do you think of th eslint rule ?
Let's go for it! We should also add a rule for the arrow function (https://github.com/mysticatea/eslint-plugin-es/blob/master/docs/rules/no-arrow-functions.md)

**Comment by ptbrowne** [comment]
> We should also add a rule for the arrow function

Why ? Arrow functions are supported in node.

```
$   nvm use 8
$   node
> () => {}
[Function]
```

**Pull request merged**
