### PR TITLE
feat(cozy-doctypes): Add isContact method to Contact model

### PR DESCRIPTION
**Pull request by cedricmessiant**
We can now use the model to determine if an object is a contact or not

### CODE REVIEW

**Comment by ptbrowne** [comment]
I am curious about the usecase here ?

**Comment by cedricmessiant** [comment]
> I am curious about the usecase here ?

In drive, we use a custom `Contact` model that also handles non-contact objects (for the sharing's recipients). I added `isContact` to this custom model but we think it may be useful to have it in the Contact model. See https://github.com/cozy/cozy-drive/pull/1640

**Comment by edas** [comment]
> In drive, we use a custom `Contact` model that also handles non-contact objects (for the sharing's recipients). I added `isContact`

isn't `instanceof Contact` enough and more generic for this?

**Comment by cedricmessiant** [comment]
> isn't `instanceof Contact` enough and more generic for this?

`Contact` is a model of contacts but our contacts objects are not instances of this model (the model is just an object that provides helpers as static methods). Am I right @ptbrowne ?

**Comment by edas** [comment]
Oh, you're right, sorry for that

**Pull request merged**
