### PR TITLE
Fix bottom content swipeable view for Harvest

### PR DESCRIPTION
**Pull request by flohhhh**
- Remove updateSwiperHeight func cause not used
- Add .idea folder in gitignore

### CODE REVIEW

**Comment by ptbrowne** [comment]
I do not understand why the function was not used, I am wondering if this would be a version problem with react-swipeable-view.

**Comment by flohhhh** [comment]
Je voulais dire plus utilisé maintenant 🙃

**Review by ptbrowne — APPROVED** [review]
Do you know the cause of the bug ? Why didn't the dom mutations method work ?

**Comment by flohhhh** [comment]
updateSwiperHeight was not called when there was a tab modification and I tried many ways to call updateHeight but no change.

I have not investigated more time on it

**Comment by flohhhh** [comment]
For information: https://www.gitmemory.com/issue/oliviertassinari/react-swipeable-views/535/520230340

**Pull request merged**
